name: Build
on: [push]
jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Setup Python
        with:
          python-version: 3.12
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .
